name: Run Notebook Daily

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC = 13:00 WIB
  workflow_dispatch:       # Bisa dijalankan manual

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Jupyter Notebook
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          papermill main.ipynb output.ipynb
